require "./stream_objects/heap"

require "./stream_objects/zero_byte_int"
require "./stream_objects/one_byte_int"
require "./stream_objects/one_byte_positive_int"
require "./stream_objects/one_byte_negative_int"
require "./stream_objects/two_byte_positive_int"
require "./stream_objects/two_byte_negative_int"
require "./stream_objects/three_byte_positive_int"
require "./stream_objects/three_byte_negative_int"
require "./stream_objects/four_byte_positive_int"
require "./stream_objects/four_byte_negative_int"

require "./stream_objects/object_pointer"
require "./stream_objects/symbol"
require "./stream_objects/string"
require "./stream_objects/array"
require "./stream_objects/null_stream_object"
require "./stream_objects/bool_stream_object"
